### ISSUE TITLE
Getting disconnected

### ISSUE THREAD

**Issue by timewarrior** [HEROLABS/herolabs-apns#7]
Hi
I have been using pans for some time and it really worked perfectly till 0.2.3. I recent upgraded to 0.5.1. Now I am frequently getting disconnected where people do not get PN. Resetting the connection object does the job. I am seeing there are many new error handlers now. Can you please let me know which error handler should I use to handle this scenario.

Thanks

**Comment by niclasmeier** [comment]
Hi,

unfortunately there was a major problem in re-connecting automatically. Imagine the following situation:
You sent 7 push messages and Apple detects that message 2 has an illegal push token and closes the network connection. The result would be, that message 3-7 would be lost and the implementation prior to the 0.5.x series would reconnect and you would never had a chance to re-sent the messages.

There is a chapter "Error handling" in the revised README.md (https://github.com/HEROLABS/herolabs-apns#error-handling) where you can find an example. This is very close to the code we use to manage our connection and re-sent messages.

**Comment by timewarrior** [comment]
Hi Niclas
Thanks for your help. I just had one question. Our use case is a very standard use-case where we have an atom as connection. We keep getting disconnect. We had supplied an error-handler but that never got called. So which handlers do we need to implement amongst channel-inactive-handler error-handler disconnect-handler.

Another thing is that in the documentation we saw that resent handler takes an argument

```
:channel-inactive-handler (resent-handler edition-id)
```

However the function definition expects no arguments:

```
(defn- resent-handler []
  (fn resent-handler-fn [_ re-sent]
    (doseq [msg re-sent] (push/sent (connection) msg))))
```

So just wanted to make sure I was understanding it correctly. This error is also non-deterministic - so its getting difficult to test what would work and what wouldn't.

Thanks for your help.

**Comment by niclasmeier** [comment]
Hi,

you can reproduce sending faulty messages quite easy e.g. by swapping two characters of the APNS token. Apple should terminate the connection, because the token does not exists (or you are somewhat lucky).

The resent-handler function from the example ist just a factory function which returns the function that will handle the re-sending. You can also use:

```
(defn resent-handler [_ re-sent]
  (doseq [msg re-sent] (push/sent (connection) msg)))
```

and pass only the function reference to the `(create-connection ...)` function.

In general the re-sent handler will be hooked in as handler function for the Netty "channelInactive" event. The function must have two parameters. The first ist the Netty `ChannelHandlerContext` which is quite internal and technical and the other is a list of all messages which where sent, after the message which was marked faulty by Apple.

The error handling function will be called when Apple sends the ID of the faulty message. I would suggest that you reset your connection Atom in this function. So the re-sent handler ist forced to re-open a connection. Additionally we delete the token in our user database to prevent it to be used again.

Additionally to the "update" of the APNS library we made a fundamental shift in our architecture. We enqueue every Apple Notification in a Rabbit MQ and have a bunch of MQ-Consumers which will keep an open connection on a per-consumer basis.
